[Gereral]
Port = 8430
Title = "Homepage"
Timezone = "Asia/Shanghai"

[[Category]]
categoryName = "APP"
items = [
    { itemName = "Blog", itemIcon = "Blog", itemLink = "#section1" },
    { itemName = "CloudDrive", itemIcon = "CloudDrive", itemLink = "#section2" },
    { itemName = "CodeServer", itemIcon = "CodeServer", itemLink = "#section3" }
]

[[Category]]
categoryName = "API"
items = [
    { itemName = "mqtt", itemIcon = "mqtt", itemLink = "#section4" },
    { itemName = "Database", itemIcon = "Database", itemLink = "#section5" }
]

[[Category]]
categoryName = "Contact"
items = [
    { itemName = "Github", itemIcon = "Github", itemLink = "#section7" },
    { itemName = "Facebook", itemIcon = "Facebook", itemLink = "#section8" },
    { itemName = "X", itemIcon = "X", itemLink = "#section9" }
]
